package github

var OtherEndpoints = map[string]string{
	"emojis":                    "https://api.github.com/emojis",
	"feeds":                     "https://api.github.com/feeds",
	"followers":                 "https://api.github.com/user/followers",
	"following":                 "https://api.github.com/user/following{/target}",
	"gists":                     "https://api.github.com/gists{/gist_id}",
	"hub":                       "https://api.github.com/hub",
	"issue_search":              "https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}",
	"issues":                    "https://api.github.com/issues",
	"keys":                      "https://api.github.com/user/keys",
	"label_search":              "https://api.github.com/search/labels?q={query}&repository_id={repository_id}{&page,per_page}",
	"notifications":             "https://api.github.com/notifications",
	"organization":              "https://api.github.com/orgs/{org}",
	"organization_repositories": "https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}",
	"organization_teams":        "https://api.github.com/orgs/{org}/teams",
	"public_gists":              "https://api.github.com/gists/public",
	"rate_limit":                "https://api.github.com/rate_limit",
	"repository":                "https://api.github.com/repos/{owner}/{repo}",
	"repository_search":         "https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}",
	"current_user_repositories": "https://api.github.com/user/repos{?type,page,per_page,sort}",
	"starred":                   "https://api.github.com/user/starred{/owner}{/repo}",
	"starred_gists":             "https://api.github.com/gists/starred",
	"topic_search":              "https://api.github.com/search/topics?q={query}{&page,per_page}",
	"user":                      "https://api.github.com/users/{user}",
	"user_organizations":        "https://api.github.com/user/orgs",
	"user_repositories":         "https://api.github.com/users/{user}/repos{?type,page,per_page,sort}",
	"user_search":               "https://api.github.com/search/users?q={query}{&page,per_page,sort,order}",
}
