// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package github

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2b897f11DecodeGitTcpDirectKayosUrastarGithub(in *jlexer.Lexer, out *Star) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "node_id":
			out.NodeId = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "full_name":
			out.FullName = string(in.String())
		case "private":
			out.Private = bool(in.Bool())
		case "owner":
			easyjson2b897f11Decode(in, &out.Owner)
		case "html_url":
			out.HtmlUrl = string(in.String())
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				*out.Description = string(in.String())
			}
		case "fork":
			out.Fork = bool(in.Bool())
		case "url":
			out.Url = string(in.String())
		case "forks_url":
			out.ForksUrl = string(in.String())
		case "keys_url":
			out.KeysUrl = string(in.String())
		case "collaborators_url":
			out.CollaboratorsUrl = string(in.String())
		case "teams_url":
			out.TeamsUrl = string(in.String())
		case "hooks_url":
			out.HooksUrl = string(in.String())
		case "issue_events_url":
			out.IssueEventsUrl = string(in.String())
		case "events_url":
			out.EventsUrl = string(in.String())
		case "assignees_url":
			out.AssigneesUrl = string(in.String())
		case "branches_url":
			out.BranchesUrl = string(in.String())
		case "tags_url":
			out.TagsUrl = string(in.String())
		case "blobs_url":
			out.BlobsUrl = string(in.String())
		case "git_tags_url":
			out.GitTagsUrl = string(in.String())
		case "git_refs_url":
			out.GitRefsUrl = string(in.String())
		case "trees_url":
			out.TreesUrl = string(in.String())
		case "statuses_url":
			out.StatusesUrl = string(in.String())
		case "languages_url":
			out.LanguagesUrl = string(in.String())
		case "stargazers_url":
			out.StargazersUrl = string(in.String())
		case "contributors_url":
			out.ContributorsUrl = string(in.String())
		case "subscribers_url":
			out.SubscribersUrl = string(in.String())
		case "subscription_url":
			out.SubscriptionUrl = string(in.String())
		case "commits_url":
			out.CommitsUrl = string(in.String())
		case "git_commits_url":
			out.GitCommitsUrl = string(in.String())
		case "comments_url":
			out.CommentsUrl = string(in.String())
		case "issue_comment_url":
			out.IssueCommentUrl = string(in.String())
		case "contents_url":
			out.ContentsUrl = string(in.String())
		case "compare_url":
			out.CompareUrl = string(in.String())
		case "merges_url":
			out.MergesUrl = string(in.String())
		case "archive_url":
			out.ArchiveUrl = string(in.String())
		case "downloads_url":
			out.DownloadsUrl = string(in.String())
		case "issues_url":
			out.IssuesUrl = string(in.String())
		case "pulls_url":
			out.PullsUrl = string(in.String())
		case "milestones_url":
			out.MilestonesUrl = string(in.String())
		case "notifications_url":
			out.NotificationsUrl = string(in.String())
		case "labels_url":
			out.LabelsUrl = string(in.String())
		case "releases_url":
			out.ReleasesUrl = string(in.String())
		case "deployments_url":
			out.DeploymentsUrl = string(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		case "pushed_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.PushedAt).UnmarshalJSON(data))
			}
		case "git_url":
			out.GitUrl = string(in.String())
		case "ssh_url":
			out.SshUrl = string(in.String())
		case "clone_url":
			out.CloneUrl = string(in.String())
		case "svn_url":
			out.SvnUrl = string(in.String())
		case "homepage":
			if in.IsNull() {
				in.Skip()
				out.Homepage = nil
			} else {
				if out.Homepage == nil {
					out.Homepage = new(string)
				}
				*out.Homepage = string(in.String())
			}
		case "size":
			out.Size = int(in.Int())
		case "stargazers_count":
			out.StargazersCount = int(in.Int())
		case "watchers_count":
			out.WatchersCount = int(in.Int())
		case "language":
			if in.IsNull() {
				in.Skip()
				out.Language = nil
			} else {
				if out.Language == nil {
					out.Language = new(string)
				}
				*out.Language = string(in.String())
			}
		case "has_issues":
			out.HasIssues = bool(in.Bool())
		case "has_projects":
			out.HasProjects = bool(in.Bool())
		case "has_downloads":
			out.HasDownloads = bool(in.Bool())
		case "has_wiki":
			out.HasWiki = bool(in.Bool())
		case "has_pages":
			out.HasPages = bool(in.Bool())
		case "forks_count":
			out.ForksCount = int(in.Int())
		case "mirror_url":
			if m, ok := out.MirrorUrl.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.MirrorUrl.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.MirrorUrl = in.Interface()
			}
		case "archived":
			out.Archived = bool(in.Bool())
		case "disabled":
			out.Disabled = bool(in.Bool())
		case "open_issues_count":
			out.OpenIssuesCount = int(in.Int())
		case "license":
			if in.IsNull() {
				in.Skip()
				out.License = nil
			} else {
				if out.License == nil {
					out.License = new(struct {
						Key    string  `json:"key"`
						Name   string  `json:"name"`
						SpdxId string  `json:"spdx_id"`
						Url    *string `json:"url"`
						NodeId string  `json:"node_id"`
					})
				}
				easyjson2b897f11Decode1(in, out.License)
			}
		case "allow_forking":
			out.AllowForking = bool(in.Bool())
		case "is_template":
			out.IsTemplate = bool(in.Bool())
		case "topics":
			if in.IsNull() {
				in.Skip()
				out.Topics = nil
			} else {
				in.Delim('[')
				if out.Topics == nil {
					if !in.IsDelim(']') {
						out.Topics = make([]string, 0, 4)
					} else {
						out.Topics = []string{}
					}
				} else {
					out.Topics = (out.Topics)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Topics = append(out.Topics, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "visibility":
			out.Visibility = string(in.String())
		case "forks":
			out.Forks = int(in.Int())
		case "open_issues":
			out.OpenIssues = int(in.Int())
		case "watchers":
			out.Watchers = int(in.Int())
		case "default_branch":
			out.DefaultBranch = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2b897f11EncodeGitTcpDirectKayosUrastarGithub(out *jwriter.Writer, in Star) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"node_id\":"
		out.RawString(prefix)
		out.String(string(in.NodeId))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"full_name\":"
		out.RawString(prefix)
		out.String(string(in.FullName))
	}
	{
		const prefix string = ",\"private\":"
		out.RawString(prefix)
		out.Bool(bool(in.Private))
	}
	{
		const prefix string = ",\"owner\":"
		out.RawString(prefix)
		easyjson2b897f11Encode(out, in.Owner)
	}
	{
		const prefix string = ",\"html_url\":"
		out.RawString(prefix)
		out.String(string(in.HtmlUrl))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		if in.Description == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Description))
		}
	}
	{
		const prefix string = ",\"fork\":"
		out.RawString(prefix)
		out.Bool(bool(in.Fork))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.Url))
	}
	{
		const prefix string = ",\"forks_url\":"
		out.RawString(prefix)
		out.String(string(in.ForksUrl))
	}
	{
		const prefix string = ",\"keys_url\":"
		out.RawString(prefix)
		out.String(string(in.KeysUrl))
	}
	{
		const prefix string = ",\"collaborators_url\":"
		out.RawString(prefix)
		out.String(string(in.CollaboratorsUrl))
	}
	{
		const prefix string = ",\"teams_url\":"
		out.RawString(prefix)
		out.String(string(in.TeamsUrl))
	}
	{
		const prefix string = ",\"hooks_url\":"
		out.RawString(prefix)
		out.String(string(in.HooksUrl))
	}
	{
		const prefix string = ",\"issue_events_url\":"
		out.RawString(prefix)
		out.String(string(in.IssueEventsUrl))
	}
	{
		const prefix string = ",\"events_url\":"
		out.RawString(prefix)
		out.String(string(in.EventsUrl))
	}
	{
		const prefix string = ",\"assignees_url\":"
		out.RawString(prefix)
		out.String(string(in.AssigneesUrl))
	}
	{
		const prefix string = ",\"branches_url\":"
		out.RawString(prefix)
		out.String(string(in.BranchesUrl))
	}
	{
		const prefix string = ",\"tags_url\":"
		out.RawString(prefix)
		out.String(string(in.TagsUrl))
	}
	{
		const prefix string = ",\"blobs_url\":"
		out.RawString(prefix)
		out.String(string(in.BlobsUrl))
	}
	{
		const prefix string = ",\"git_tags_url\":"
		out.RawString(prefix)
		out.String(string(in.GitTagsUrl))
	}
	{
		const prefix string = ",\"git_refs_url\":"
		out.RawString(prefix)
		out.String(string(in.GitRefsUrl))
	}
	{
		const prefix string = ",\"trees_url\":"
		out.RawString(prefix)
		out.String(string(in.TreesUrl))
	}
	{
		const prefix string = ",\"statuses_url\":"
		out.RawString(prefix)
		out.String(string(in.StatusesUrl))
	}
	{
		const prefix string = ",\"languages_url\":"
		out.RawString(prefix)
		out.String(string(in.LanguagesUrl))
	}
	{
		const prefix string = ",\"stargazers_url\":"
		out.RawString(prefix)
		out.String(string(in.StargazersUrl))
	}
	{
		const prefix string = ",\"contributors_url\":"
		out.RawString(prefix)
		out.String(string(in.ContributorsUrl))
	}
	{
		const prefix string = ",\"subscribers_url\":"
		out.RawString(prefix)
		out.String(string(in.SubscribersUrl))
	}
	{
		const prefix string = ",\"subscription_url\":"
		out.RawString(prefix)
		out.String(string(in.SubscriptionUrl))
	}
	{
		const prefix string = ",\"commits_url\":"
		out.RawString(prefix)
		out.String(string(in.CommitsUrl))
	}
	{
		const prefix string = ",\"git_commits_url\":"
		out.RawString(prefix)
		out.String(string(in.GitCommitsUrl))
	}
	{
		const prefix string = ",\"comments_url\":"
		out.RawString(prefix)
		out.String(string(in.CommentsUrl))
	}
	{
		const prefix string = ",\"issue_comment_url\":"
		out.RawString(prefix)
		out.String(string(in.IssueCommentUrl))
	}
	{
		const prefix string = ",\"contents_url\":"
		out.RawString(prefix)
		out.String(string(in.ContentsUrl))
	}
	{
		const prefix string = ",\"compare_url\":"
		out.RawString(prefix)
		out.String(string(in.CompareUrl))
	}
	{
		const prefix string = ",\"merges_url\":"
		out.RawString(prefix)
		out.String(string(in.MergesUrl))
	}
	{
		const prefix string = ",\"archive_url\":"
		out.RawString(prefix)
		out.String(string(in.ArchiveUrl))
	}
	{
		const prefix string = ",\"downloads_url\":"
		out.RawString(prefix)
		out.String(string(in.DownloadsUrl))
	}
	{
		const prefix string = ",\"issues_url\":"
		out.RawString(prefix)
		out.String(string(in.IssuesUrl))
	}
	{
		const prefix string = ",\"pulls_url\":"
		out.RawString(prefix)
		out.String(string(in.PullsUrl))
	}
	{
		const prefix string = ",\"milestones_url\":"
		out.RawString(prefix)
		out.String(string(in.MilestonesUrl))
	}
	{
		const prefix string = ",\"notifications_url\":"
		out.RawString(prefix)
		out.String(string(in.NotificationsUrl))
	}
	{
		const prefix string = ",\"labels_url\":"
		out.RawString(prefix)
		out.String(string(in.LabelsUrl))
	}
	{
		const prefix string = ",\"releases_url\":"
		out.RawString(prefix)
		out.String(string(in.ReleasesUrl))
	}
	{
		const prefix string = ",\"deployments_url\":"
		out.RawString(prefix)
		out.String(string(in.DeploymentsUrl))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"pushed_at\":"
		out.RawString(prefix)
		out.Raw((in.PushedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"git_url\":"
		out.RawString(prefix)
		out.String(string(in.GitUrl))
	}
	{
		const prefix string = ",\"ssh_url\":"
		out.RawString(prefix)
		out.String(string(in.SshUrl))
	}
	{
		const prefix string = ",\"clone_url\":"
		out.RawString(prefix)
		out.String(string(in.CloneUrl))
	}
	{
		const prefix string = ",\"svn_url\":"
		out.RawString(prefix)
		out.String(string(in.SvnUrl))
	}
	{
		const prefix string = ",\"homepage\":"
		out.RawString(prefix)
		if in.Homepage == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Homepage))
		}
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.Int(int(in.Size))
	}
	{
		const prefix string = ",\"stargazers_count\":"
		out.RawString(prefix)
		out.Int(int(in.StargazersCount))
	}
	{
		const prefix string = ",\"watchers_count\":"
		out.RawString(prefix)
		out.Int(int(in.WatchersCount))
	}
	{
		const prefix string = ",\"language\":"
		out.RawString(prefix)
		if in.Language == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Language))
		}
	}
	{
		const prefix string = ",\"has_issues\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasIssues))
	}
	{
		const prefix string = ",\"has_projects\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasProjects))
	}
	{
		const prefix string = ",\"has_downloads\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasDownloads))
	}
	{
		const prefix string = ",\"has_wiki\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasWiki))
	}
	{
		const prefix string = ",\"has_pages\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasPages))
	}
	{
		const prefix string = ",\"forks_count\":"
		out.RawString(prefix)
		out.Int(int(in.ForksCount))
	}
	{
		const prefix string = ",\"mirror_url\":"
		out.RawString(prefix)
		if m, ok := in.MirrorUrl.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.MirrorUrl.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.MirrorUrl))
		}
	}
	{
		const prefix string = ",\"archived\":"
		out.RawString(prefix)
		out.Bool(bool(in.Archived))
	}
	{
		const prefix string = ",\"disabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.Disabled))
	}
	{
		const prefix string = ",\"open_issues_count\":"
		out.RawString(prefix)
		out.Int(int(in.OpenIssuesCount))
	}
	{
		const prefix string = ",\"license\":"
		out.RawString(prefix)
		if in.License == nil {
			out.RawString("null")
		} else {
			easyjson2b897f11Encode1(out, *in.License)
		}
	}
	{
		const prefix string = ",\"allow_forking\":"
		out.RawString(prefix)
		out.Bool(bool(in.AllowForking))
	}
	{
		const prefix string = ",\"is_template\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsTemplate))
	}
	{
		const prefix string = ",\"topics\":"
		out.RawString(prefix)
		if in.Topics == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Topics {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"visibility\":"
		out.RawString(prefix)
		out.String(string(in.Visibility))
	}
	{
		const prefix string = ",\"forks\":"
		out.RawString(prefix)
		out.Int(int(in.Forks))
	}
	{
		const prefix string = ",\"open_issues\":"
		out.RawString(prefix)
		out.Int(int(in.OpenIssues))
	}
	{
		const prefix string = ",\"watchers\":"
		out.RawString(prefix)
		out.Int(int(in.Watchers))
	}
	{
		const prefix string = ",\"default_branch\":"
		out.RawString(prefix)
		out.String(string(in.DefaultBranch))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Star) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2b897f11EncodeGitTcpDirectKayosUrastarGithub(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Star) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2b897f11EncodeGitTcpDirectKayosUrastarGithub(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Star) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2b897f11DecodeGitTcpDirectKayosUrastarGithub(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Star) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2b897f11DecodeGitTcpDirectKayosUrastarGithub(l, v)
}
func easyjson2b897f11Decode1(in *jlexer.Lexer, out *struct {
	Key    string  `json:"key"`
	Name   string  `json:"name"`
	SpdxId string  `json:"spdx_id"`
	Url    *string `json:"url"`
	NodeId string  `json:"node_id"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "key":
			out.Key = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "spdx_id":
			out.SpdxId = string(in.String())
		case "url":
			if in.IsNull() {
				in.Skip()
				out.Url = nil
			} else {
				if out.Url == nil {
					out.Url = new(string)
				}
				*out.Url = string(in.String())
			}
		case "node_id":
			out.NodeId = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2b897f11Encode1(out *jwriter.Writer, in struct {
	Key    string  `json:"key"`
	Name   string  `json:"name"`
	SpdxId string  `json:"spdx_id"`
	Url    *string `json:"url"`
	NodeId string  `json:"node_id"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix[1:])
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"spdx_id\":"
		out.RawString(prefix)
		out.String(string(in.SpdxId))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		if in.Url == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Url))
		}
	}
	{
		const prefix string = ",\"node_id\":"
		out.RawString(prefix)
		out.String(string(in.NodeId))
	}
	out.RawByte('}')
}
func easyjson2b897f11Decode(in *jlexer.Lexer, out *struct {
	Login             string `json:"login"`
	Id                int    `json:"id"`
	AvatarUrl         string `json:"avatar_url"`
	Url               string `json:"url"`
	HtmlUrl           string `json:"html_url"`
	FollowersUrl      string `json:"followers_url"`
	FollowingUrl      string `json:"following_url"`
	GistsUrl          string `json:"gists_url"`
	StarredUrl        string `json:"starred_url"`
	SubscriptionsUrl  string `json:"subscriptions_url"`
	OrganizationsUrl  string `json:"organizations_url"`
	ReposUrl          string `json:"repos_url"`
	EventsUrl         string `json:"events_url"`
	ReceivedEventsUrl string `json:"received_events_url"`
	Type              string `json:"type"`
	SiteAdmin         bool   `json:"site_admin"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "login":
			out.Login = string(in.String())
		case "id":
			out.Id = int(in.Int())
		case "avatar_url":
			out.AvatarUrl = string(in.String())
		case "url":
			out.Url = string(in.String())
		case "html_url":
			out.HtmlUrl = string(in.String())
		case "followers_url":
			out.FollowersUrl = string(in.String())
		case "following_url":
			out.FollowingUrl = string(in.String())
		case "gists_url":
			out.GistsUrl = string(in.String())
		case "starred_url":
			out.StarredUrl = string(in.String())
		case "subscriptions_url":
			out.SubscriptionsUrl = string(in.String())
		case "organizations_url":
			out.OrganizationsUrl = string(in.String())
		case "repos_url":
			out.ReposUrl = string(in.String())
		case "events_url":
			out.EventsUrl = string(in.String())
		case "received_events_url":
			out.ReceivedEventsUrl = string(in.String())
		case "type":
			out.Type = string(in.String())
		case "site_admin":
			out.SiteAdmin = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2b897f11Encode(out *jwriter.Writer, in struct {
	Login             string `json:"login"`
	Id                int    `json:"id"`
	AvatarUrl         string `json:"avatar_url"`
	Url               string `json:"url"`
	HtmlUrl           string `json:"html_url"`
	FollowersUrl      string `json:"followers_url"`
	FollowingUrl      string `json:"following_url"`
	GistsUrl          string `json:"gists_url"`
	StarredUrl        string `json:"starred_url"`
	SubscriptionsUrl  string `json:"subscriptions_url"`
	OrganizationsUrl  string `json:"organizations_url"`
	ReposUrl          string `json:"repos_url"`
	EventsUrl         string `json:"events_url"`
	ReceivedEventsUrl string `json:"received_events_url"`
	Type              string `json:"type"`
	SiteAdmin         bool   `json:"site_admin"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"login\":"
		out.RawString(prefix[1:])
		out.String(string(in.Login))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		out.String(string(in.AvatarUrl))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.Url))
	}
	{
		const prefix string = ",\"html_url\":"
		out.RawString(prefix)
		out.String(string(in.HtmlUrl))
	}
	{
		const prefix string = ",\"followers_url\":"
		out.RawString(prefix)
		out.String(string(in.FollowersUrl))
	}
	{
		const prefix string = ",\"following_url\":"
		out.RawString(prefix)
		out.String(string(in.FollowingUrl))
	}
	{
		const prefix string = ",\"gists_url\":"
		out.RawString(prefix)
		out.String(string(in.GistsUrl))
	}
	{
		const prefix string = ",\"starred_url\":"
		out.RawString(prefix)
		out.String(string(in.StarredUrl))
	}
	{
		const prefix string = ",\"subscriptions_url\":"
		out.RawString(prefix)
		out.String(string(in.SubscriptionsUrl))
	}
	{
		const prefix string = ",\"organizations_url\":"
		out.RawString(prefix)
		out.String(string(in.OrganizationsUrl))
	}
	{
		const prefix string = ",\"repos_url\":"
		out.RawString(prefix)
		out.String(string(in.ReposUrl))
	}
	{
		const prefix string = ",\"events_url\":"
		out.RawString(prefix)
		out.String(string(in.EventsUrl))
	}
	{
		const prefix string = ",\"received_events_url\":"
		out.RawString(prefix)
		out.String(string(in.ReceivedEventsUrl))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"site_admin\":"
		out.RawString(prefix)
		out.Bool(bool(in.SiteAdmin))
	}
	out.RawByte('}')
}
